<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

<h1>Extracting and Visualizing Stock Data</h1>
<h2>Description</h2>

Extracting essential data from a dataset and displaying it is a necessary part of data science; therefore individuals can make correct decisions based on the data. In this assignment, you will extract some stock data, you will then display this data in a graph.

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>Define a Function that Makes a Graph</li>
        <li>Question 1: Use yfinance to Extract Stock Data</li>
        <li>Question 2: Use Webscraping to Extract Tesla Revenue Data</li>
        <li>Question 3: Use yfinance to Extract Stock Data</li>
        <li>Question 4: Use Webscraping to Extract GME Revenue Data</li>
        <li>Question 5: Plot Tesla Stock Graph</li>
        <li>Question 6: Plot GameStop Stock Graph</li>
    </ul>
<p>
    Estimated Time Needed: <strong>30 min</strong></p>
</div>

<hr>

In [1]:
!pip install yfinance==0.1.67
#!pip install pandas==1.3.3
#!pip install requests==2.26.0
!mamba install bs4==4.10.0 -y
#!pip install plotly==5.3.1
!pip install html5lib

Collecting yfinance==0.1.67
  Downloading yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: pandas>=0.24 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.3.5)
Requirement already satisfied: requests>=2.20 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (2.28.1)
Requirement already satisfied: lxml>=4.5.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (4.9.1)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: numpy>=1.15 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2022.5)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.4)
Requirement already satisfied: six>=1.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance==0.1.67) (1.16.0)
Installing collected packages: multitasking, yfinance
Successfully installed multitasking-0.0.11 yfinance-0.1.67

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bs4==4.10.0']

pkgs/r/linux-64          [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/main/noarch         [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/main/noarch         [=>                ] (00m:00s) 616 KB / ?? (1.92 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/main/noarch         [<=>                 ] (00m:00s) Finalizing...
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/main/noarch         [<=>                 ] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [=>                ] (00m:00s) 624 KB / ?? (1.98 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [<=>                 ] (00m:00s) Finalizing...
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/r/noarch            [<=>                 ] (00m:00s) Done
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/main/linux-64       [=>                ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/main/linux-64       [<=>               ] (00m:00s) 324 KB / ?? (1.02 MB/s)
pkgs/r/linux-64          [=>                ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/main/linux-64       [<=>               ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/r/linux-64          [<=>               ] (00m:00s) 668 KB / ?? (2.13 MB/s)
pkgs/main/linux-64       [<=>               ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/r/linux-64          [ <=>                ] (00m:00s) 1 MB / ?? (2.76 MB/s)
pkgs/main/linux-64       [<=>               ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/r/linux-64          [ <=>                ] (00m:00s) Finalizing...
pkgs/main/linux-64       [<=>               ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/r/linux-64          [ <=>                ] (00m:00s) Done
pkgs/main/linux-64       [<=>               ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/main/linux-64       [<=>               ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/main/linux-64       [ <=>              ] (00m:00s) 748 KB / ?? (1.55 MB/s)
pkgs/main/linux-64       [  <=>               ] (00m:00s) 1 MB / ?? (2.02 MB/s)
pkgs/main/linux-64       [   <=>              ] (00m:00s) 1 MB / ?? (2.02 MB/s)
pkgs/main/linux-64       [   <=>              ] (00m:00s) 2 MB / ?? (2.21 MB/s)
pkgs/main/linux-64       [    <=>             ] (00m:00s) 2 MB / ?? (2.21 MB/s)
pkgs/main/linux-64       [    <=>             ] (00m:00s) 2 MB / ?? (2.32 MB/s)
pkgs/main/linux-64       [     <=>            ] (00m:00s) 2 MB / ?? (2.32 MB/s)
pkgs/main/linux-64       [     <=>            ] (00m:00s) 3 MB / ?? (2.38 MB/s)
pkgs/main/linux-64       [      <=>           ] (00m:00s) 3 MB / ?? (2.38 MB/s)
pkgs/main/linux-64       [      <=>           ] (00m:00s) 3 MB / ?? (2.45 MB/s)
pkgs/main/linux-64       [       <=>          ] (00m:01s) 3 MB / ?? (2.45 MB/s)
pkgs/main/linux-64       [       <=>          ] (00m:01s) 3 MB / ?? (2.31 MB/s)
pkgs/main/linux-64       [        <=>         ] (00m:01s) 3 MB / ?? (2.31 MB/s)
pkgs/main/linux-64       [        <=>         ] (00m:01s) 4 MB / ?? (2.57 MB/s)
pkgs/main/linux-64       [         <=>        ] (00m:01s) 4 MB / ?? (2.57 MB/s)
pkgs/main/linux-64       [         <=>        ] (00m:01s) 4 MB / ?? (2.60 MB/s)
pkgs/main/linux-64       [         <=>        ] (00m:01s) Finalizing...
pkgs/main/linux-64       [         <=>        ] (00m:01s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - bs4==4.10.0
   - ca-certificates
   - certifi
   - openssl


  Package               Version  Build           Channel                  Size
────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────

  + bs4                  4.10.0  hd3eb1b0_0      pkgs/main/noarch        10 KB

  Change:
────────────────────────────────────────────────────────────────────────────────

  - certifi           2022.9.24  pyhd8ed1ab_0    installed
  + certifi           2022.9.24  py37h06a4308_0  pkgs/main/linux-64     154 KB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────

  - ca-certificates   2022.9.24  ha878542_0      installed
  + ca-certificates  2022.10.11  h06a4308_0      pkgs/main/linux-64     124 KB
  - openssl              1.1.1q  h166bdaf_1      installed
  + openssl              1.1.1s  h7f8727e_0      pkgs/main/linux-64       4 MB

  Downgrade:
────────────────────────────────────────────────────────────────────────────────

  - beautifulsoup4       4.11.1  pyha770c72_0    installed
  + beautifulsoup4       4.10.0  pyh06a4308_0    pkgs/main/noarch        85 KB

  Summary:

  Install: 1 packages
  Change: 1 packages
  Upgrade: 2 packages
  Downgrade: 1 packages

  Total download: 4 MB

────────────────────────────────────────────────────────────────────────────────

Downloading  [>                                        ] (00m:00s)  452.01 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [>                                                      ] (--:--)
Finished beautifulsoup4                       (00m:00s)              85 KB    451 KB/s
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [>                                                      ] (--:--)
Finished bs4                                  (00m:00s)              10 KB     57 KB/s
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [>                                        ] (00m:00s)  502.83 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [==>                                      ] (00m:00s)    1.13 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Finished certifi                              (00m:00s)             154 KB    756 KB/s
Downloading  [==>                                      ] (00m:00s)    1.13 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [==>                                      ] (00m:00s)    1.13 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [==>                                      ] (00m:00s)    1.13 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [==>                                      ] (00m:00s)    1.13 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [===>                                     ] (00m:00s)    1.54 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Finished ca-certificates                      (00m:00s)             124 KB    551 KB/s
Downloading  [===>                                     ] (00m:00s)    1.54 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [===>                                     ] (00m:00s)    1.54 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [===>                                     ] (00m:00s)    1.54 MB/s
Extracting   [========================>                ] (00m:00s)        3 / 5
Downloading  [===>                                     ] (00m:00s)    1.54 MB/s
Extracting   [========================>                ] (00m:00s)        3 / 5
Downloading  [===>                                     ] (00m:00s)    1.54 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   13.45 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Finished openssl                              (00m:00s)               4 MB     13 MB/s
Downloading  [=========================================] (00m:00s)   13.45 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   13.45 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   13.45 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   13.45 MB/s
Extracting   [=========================================] (00m:00s)        5 / 5
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 9.9 MB/s eta 0:00:00
Requirement already satisfied: webencodings in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from html5lib) (1.16.0)
Installing collected packages: html5lib
Successfully installed html5lib-1.1

In [2]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import html5lib

## Define Graphing Function

In this section, we define the function `make_graph`. You don't have to know how the function works, you should only care about the inputs. It takes a dataframe with stock data (dataframe must contain Date and Close columns), a dataframe with revenue data (dataframe must contain Date and Revenue columns), and the name of the stock.

In [3]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021--06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

## Question 1: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is Tesla and its ticker symbol is `TSLA`.

In [4]:
tesla=yf.Ticker("TSLA")

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `tesla_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [5]:
tesla_data=tesla.history(period='max')

**Reset the index** using the `reset_index(inplace=True)` function on the tesla_data DataFrame and display the first five rows of the `tesla_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 1 to the results below.

In [6]:
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29,1.266667,1.666667,1.169333,1.592667,281494500,0,0.0
1,2010-06-30,1.719333,2.028000,1.553333,1.588667,257806500,0,0.0
2,2010-07-01,1.666667,1.728000,1.351333,1.464000,123282000,0,0.0
3,2010-07-02,1.533333,1.540000,1.247333,1.280000,77097000,0,0.0
4,2010-07-06,1.333333,1.333333,1.055333,1.074000,103003500,0,0.0

## Question 2: Use Webscraping to Extract Tesla Revenue Data

Use the `requests` library to download the webpage [https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue](https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0220ENSkillsNetwork23455606-2022-01-01). Save the text of the response as a variable named `html_data`.

In [7]:
url='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'
tesla_html_data=requests.get(url).text

Parse the html data using `beautiful_soup`.

In [8]:
soup=BeautifulSoup(tesla_html_data,'html.parser')

Using `BeautifulSoup` or the `read_html` function extract the table with `Tesla Quarterly Revenue` and store it into a dataframe named `tesla_revenue`. The dataframe should have columns `Date` and `Revenue`.

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

In [9]:
#create DataFrame using read_html
read_html_tesla_data=pd.read_html(url)
tesla_revenue = read_html_tesla_data[1]
#to make DataFrame have columns Date and Revenue by using rename function
tesla_revenue = tesla_revenue.rename(columns={'Tesla Quarterly Revenue(Millions of US $)':'Date','Tesla Quarterly Revenue(Millions of US $).1':'Revenue'})
tesla_revenue.head()

         Date  Revenue
0  2022-09-30  $21,454
1  2022-06-30  $16,934
2  2022-03-31  $18,756
3  2021-12-31  $17,719
4  2021-09-30  $13,757

Execute the following line to remove the comma and dollar sign from the `Revenue` column.

In [27]:
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning:

The default value of regex will change from True to False in a future version.

Execute the following lines to remove an null or empty strings in the Revenue column.

In [25]:
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

Display the last 5 row of the `tesla_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [26]:
tesla_revenue.tail()

          Date Revenue
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

## Question 3: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is GameStop and its ticker symbol is `GME`.

In [13]:
gamestop=yf.Ticker("GME")

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `gme_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [14]:
gme_data = gamestop.history(period='max')

**Reset the index** using the `reset_index(inplace=True)` function on the gme_data DataFrame and display the first five rows of the `gme_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 3 to the results below.

In [15]:
gme_data.reset_index(inplace=True)
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

## Question 4: Use Webscraping to Extract GME Revenue Data

Use the `requests` library to download the webpage <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html>. Save the text of the response as a variable named `html_data`.

Parse the html data using `beautiful_soup`.

In [20]:
url = 'https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0220ENSkillsNetwork23455606-2021-01-01'
html_data = requests.get(url).text

Using `BeautifulSoup` or the `read_html` function extract the table with `GameStop Quarterly Revenue` and store it into a dataframe named `gme_revenue`. The dataframe should have columns `Date` and `Revenue`. Make sure the comma and dollar sign is removed from the `Revenue` column using a method similar to what you did in Question 2.

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

In [21]:
soup=BeautifulSoup(html_data,'html5lib')

Display the last five rows of the `gme_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [34]:

#create DataFrame using read_html
read_html_gme_data=pd.read_html(url)
gme_revenue = read_html_gme_data[1]
#to make DataFrame have columns Date and Revenue by using rename function
gme_revenue = gme_revenue.rename(columns={'GameStop Quarterly Revenue(Millions of US $)':'Date','GameStop Quarterly Revenue(Millions of US $).1':'Revenue'})
gme_revenue.head()
gme_revenue.tail()

gme_revenue["Revenue"] = gme_revenue['Revenue'].str.replace(',|\$',"")

gme_revenue.dropna(inplace=True)

gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]

gme_revenue

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning:

The default value of regex will change from True to False in a future version.

          Date Revenue
0   2022-07-31    1136
1   2022-04-30    1378
2   2022-01-31    2254
3   2021-10-31    1297
4   2021-07-31    1183
5   2021-04-30    1277
6   2021-01-31    2122
7   2020-10-31    1005
8   2020-07-31     942
9   2020-04-30    1021
10  2020-01-31    2194
11  2019-10-31    1439
12  2019-07-31    1286
13  2019-04-30    1548
14  2019-01-31    3063
15  2018-10-31    1935
16  2018-07-31    1501
17  2018-04-30    1786
18  2018-01-31    2825
19  2017-10-31    1989
20  2017-07-31    1688
21  2017-04-30    2046
22  2017-01-31    2403
23  2016-10-31    1959
24  2016-07-31    1632
25  2016-04-30    1972
26  2016-01-31    3525
27  2015-10-31    2016
28  2015-07-31    1762
29  2015-04-30    2061
30  2015-01-31    3476
31  2014-10-31    2092
32  2014-07-31    1731
33  2014-04-30    1996
34  2014-01-31    3684
35  2013-10-31    2107
36  2013-07-31    1384
37  2013-04-30    1865
38  2013-01-31    3562
39  2012-10-31    1773
40  2012-07-31    1550
41  2012-04-30    2002
42  2012-01-31    3579
43  2011-10-31    1947
44  2011-07-31    1744
45  2011-04-30    2281
46  2011-01-31    3693
47  2010-10-31    1899
48  2010-07-31    1799
49  2010-04-30    2083
50  2010-01-31    3524
51  2009-10-31    1835
52  2009-07-31    1739
53  2009-04-30    1981
54  2009-01-31    3492

In [35]:
gme_revenue.tail()

          Date Revenue
50  2010-01-31    3524
51  2009-10-31    1835
52  2009-07-31    1739
53  2009-04-30    1981
54  2009-01-31    3492

## Question 5: Plot Tesla Stock Graph

Use the `make_graph` function to graph the Tesla Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(tesla_data, tesla_revenue, 'Tesla')`. Note the graph will only show data upto June 2021.

In [24]:
make_graph(gme_data, gme_revenue, 'gme')

AttributeError: 'DataFrame' object has no attribute 'Date'

## Question 6: Plot GameStop Stock Graph

Use the `make_graph` function to graph the GameStop Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(gme_data, gme_revenue, 'GameStop')`. Note the graph will only show data upto June 2021.

In [ ]:
make_graph(gme_data, gme_revenue, gamestop)

<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0220ENSkillsNetwork23455606-2022-01-01">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Azim Hirjani

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description          |
| ----------------- | ------- | ------------- | --------------------------- |
| 2022-02-28        | 1.2     | Lakshmi Holla | Changed the URL of GameStop |
| 2020-11-10        | 1.1     | Malika Singla | Deleted the Optional part   |
| 2020-08-27        | 1.0     | Malika Singla | Added lab to GitLab         |

<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

<p>